const express = require('express')
const router = express.Router()
const userRoutes = require('../modules/users/user.routes')
const lecturerRoutes = require('../modules/lecturers/lecturer.routes')
const authRoutes = require('../modules/auth/auth.routes')
const { authMiddleware } = require('../common/middlewares/auth.middleware')
const roleRoutes = require('../modules/roles/role.routes')
const permissionRoutes = require('../modules/permissions/permission.routes')
const studyProgramRoutes = require('../modules/study-programs/study-program.routes')
const roomRoutes = require('../modules/rooms/room.routes')
const buildingRoutes = require('../modules/buildings/building.routes')
const deviceRoutes = require('../modules/devices/device.routes')
const masterFloorRoutes = require('../modules/floors/floor.routes')

router.use('/auth', authRoutes)

router.use('/users', authMiddleware, userRoutes)
router.use('/lecturers', authMiddleware, lecturerRoutes)
router.use('/roles', authMiddleware, roleRoutes)
router.use('/permissions', permissionRoutes)
router.use('/study-programs', authMiddleware, studyProgramRoutes)
router.use('/rooms', authMiddleware, roomRoutes)
router.use('/buildings', authMiddleware, buildingRoutes)
router.use('/devices', authMiddleware, deviceRoutes)
router.use('/floors', authMiddleware, masterFloorRoutes)

module.exports = router
